export const translate = {
    ar: {
        HomePageTopTitle: "المصدر المفضل لديك للرسائل القصيرة المجانية",
        HomePageTopMiniTitle:
            "استمتع الان بتجربة الرسائل المجانيه تواصل مع عملاءك واصدقاءك اسرع",
        FindOutMore: "اكتشف المزيد",
        About: "عن الموقع",
        Contect: "تواصل معنا",
        Login: "تسجيل دخول",
        Register: "تسجيل جديد",
        Registion: "تسجيل جديد",

        Wevegotwhatyouneed: "لدينا ما تحتاجه!",
        WevegotwhatyouneedD:
            "فعل حسابك الان و ابدأ في ارسال الرسائل الجانيه , ادعي صحابك لتسجيل في الموقع واحصل علي المزيد من الرسائل المجانيه",
        StartNow: "ابدأ الان",
        AtYourService: "في خدمتكم",
        SturdySystem: "نظام قوي",
        SturdySystemD: "يتم تحديث نظامنا بانتظام لإبقائها خالية من الأخطاء!",
        UpToDate: "حتى الآن",
        Dep: "يتم تحديث جميع التبعيات لإبقاء الأشياء جديدة.",
        Red: "جاهز للإستخدام",
        RedD: "يمكنك استخدام هذا كل يوم",
        Love: "مصنوع بحب",
        LoveD: "حتي نساعد الجميع",
        S: "بداية مجانية",
        C: "دعونا الحصول على اتصال!",
        CD: "اذا كنت تواجه اي مشكله او تريد المساعد كلمنا",
        fn: "الاسم الكامل",
        ea: "عنوان البريد الالكترونى",
        pn: "رقم الهاتف",
        pw: "كلمه السر",
        ca: "إنشاء حساب",
        ha: "لديك حساب",
        li: "تسجيل الان",
        lw: "انضم إلينا الآن واستمتع بالرسائل المجانية.",
        rerr: `الرجاء تقع جميع المعلومات ، وينبغي
        تمرير وإعادة تمرير نفس القيمة.`,
        TTCN: "تم إرسال رسالة نصية قصيرة تحتوي على كود إلى رقمك ، لتفعيل الرقم",
        Ck: "تاكيد",
        bk: "رجوع",
        cerr: "رمز غير صحيح",
        rsc: "اعاده ارسال",
        fg: "نسيت الباسورد",
        sc: "ارسال الكود",
        ForGetCodeERror: "الكود خطأ",
        errPass: "بريد أو كلمة مرورغير صحيحة",
        code: "الكود",
        SendNow: "ارسل الان",
        FreeSendDesc: `يمكنك إرسال رسائل مجانية إلى أصدقائك و
        عائلتك`,
        SMSRemains: "الرسائل المتبيقه",
        Profile: "الملف الشخصي",
        update: "تحديث",
        fail: "فشل",
        success: "نجاح",
        ContectUs: "تواصل معانا",
        subject: "الموضوع",
        choose: "اختر",
        feedback: "ردود الفعل",
        rab: "تبليغ عن مشكله",
        fq: "طلب المواصفات",
        message: "الرساله",
        SendDesc: `أرسل رسالتك النصية إلى أي شخص في جميع أنحاء العالم مجانًا من خلال موقعنا
        خدمة الرسائل القصيرة الدولية. أرسل رسائل قصيرة مجانية على الفور
        مع خدمة الرسائل القصيرة السريعة بشكل لا يصدق. العالم أفضل و
        أسرع خدمة رسائل نصية عبر الإنترنت!`,
        earnDesc:
            "الآن يمكنك كسب المزيد من الرسائل المجانية. شارك هذا الرابط مع أصدقائك واكسب رسائل ، وسيحصلون أيضًا على رسالة جديدة.",
        link: "الرابط الخاص بك",

        DashBoard: "لوحة التحكم",
        logout: "تسجيل خروج",
        home: "الصفحه الرسية",
        sendsms: "ارسال رساله",
        freeSms: "رسائل مجانا",
        Products: "منتجات"
    },

    fr: {
        HomePageTopTitle: "VOTRE SOURCE PRÉFÉRÉE DE SMS GRATUITS",
        HomePageTopMiniTitle:
            "Profitez maintenant de l'expérience SMS gratuite. Connectez-vous plus rapidement avec vos clients et amis",
        FindOutMore: "En savoir plus",
        About: "À propos du site",
        Contect: "Contactez nous",
        Login: "S'identifier",
        Register: "nouvelle inscription",
        Registion: "nouvelle inscription",

        Wevegotwhatyouneed: "Nous avons ce dont vous avez besoin!",
        WevegotwhatyouneedD:
            "Activez votre compte maintenant et commencez à envoyer les messages criminels, invitez vos amis à s'inscrire sur le site et recevez plus de messages gratuits",
        StartNow: "commencez maintenant",
        AtYourService: "À votre service",
        SturdySystem: "Système robuste",
        SturdySystemD:
            "Notre système est mis à jour régulièrement pour les garder sans bogue!",
        UpToDate: "À jour",
        Dep:
            "Toutes les dépendances sont tenues à jour pour garder les choses fraîches.",
        Red: "Prêt à l'emploi",
        RedD: "vous pouvez l'utiliser tous les jours",
        Love: "Fait avec amour",
        LoveD: "Pour que nous puissions aider tout le monde",
        S: "Départ gratuit",
        C: "Entrons en contact!",
        CD:
            "Si vous rencontrez un problème ou souhaitez une aide, appelez-nous",
        fn: "nom complet",
        ea: "adresse e-mail",
        pn: "numéro de téléphone",
        pw: "mot de passe",
        ca: "créer un compte",
        ha: "Avoir un compte?",
        li: "s'identifier",
        lw: "Rejoignez-nous maintenant et profitez des messages gratuits.",
        rerr: `S'il vous plaît tomber toutes les informations, et devrait
        Passer et repasser a la même valeur.`,
        TTCN:
            "Nous avons été Envoyer des sms avec le code à votre numéro, pour virtifier le numéro",
        Ck: "vérifier",
        bk: "arrière",
        cerr: "le code incorrect",
        rsc: "renvoyer le code",
        fg: "mot de passe oublié",
        sc: "envoyer le code",
        ForGetCodeERror: "un code correct",
        errPass: "email ou mot de passe incorrect",
        code: "code",
        SendNow: "envoyer maintenant",
        FreeSendDesc: `Vous pouvez envoyer des messages gratuits à vos amis et à votre famille`,
        SMSRemains: "reste des messages",
        Profile: "Profil personnel",
        update: "Mise à jour",
        fail: "Échouer",
        success: "Succès",
        ContectUs: "Connecte-toi avec nous",
        subject: "Matière",
        choose: "Choisir",
        feedback: "Retour d'information",
        rab: "Signaler un problème",
        fq: "Demande de spécification",
        message: "le message",
        SendDesc: `Envoyez votre message texte à n'importe qui dans le monde gratuitement via notre site Web
        Service SMS international. Envoyez des SMS gratuits instantanément
        Avec un service SMS incroyablement rapide. Le monde est meilleur et
        Le service de messagerie texte en ligne le plus rapide!`,
        earnDesc:
            "Vous pouvez désormais gagner plus de messages gratuits. Partagez ce lien avec vos amis, gagnez des messages et ils recevront également un nouveau message.",
        link: "Votre lien",
        DashBoard: "Tableau de bord",

        logout: "Se déconnecter",
        home: "domicile",
        sendsms: "envoyer un SMS",
        freeSms: "SMS gratuit",
        Products: "Des produits"
    },
    en: {
        HomePageTopTitle: "YOUR FAVORITE SOURCE OF FREE SMS",
        HomePageTopMiniTitle:
            "Now enjoy the free SMS experience. Connect faster with your customers and friends",
        FindOutMore: "Learn more",
        About: "About the site",
        Contect: "Contact us",
        Login: "Login",
        Register: "new registration",
        Registion: "new registration",

        Wevegotwhatyouneed: "We have what you need!",
        WevegotwhatyouneedD:
            "Activate your account now and start sending the criminal messages, invite your friends to register on the site and get more free messages",
        StartNow: "start now",
        AtYourService: "At your service",
        SturdySystem: "Robust system",
        SturdySystemD: "Our system is updated regularly to keep them bug free!",
        UpToDate: "Up to date",
        Dep: "All outbuildings are kept up to date to keep things fresh.",
        Red: "Ready to use",
        RedD: "you can use it everyday",
        Love: "Made with love",
        LoveD: "So that we can help everyone",
        S: "Free departure",
        C: "Let's get in touch!",
        CD: "If you have a problem or want help, give us a call",
        fn: "Full Name",
        ea: "E-mail adress",
        pn: "phone number",
        pw: "password",
        ca: "create an account",
        ha: "Have an account?",
        li: "Login",
        lw: "Join us now and enjoy free messages.",
        rerr: `Please drop all information, and should
        Pass and password has the same value.`,
        TTCN:
            "We have been sending sms with the code to your number, to virtualize the number",
        Ck: "verify",
        bk: "back",
        cerr: "the wrong code",
        rsc: "Return the code",
        fg: "Forgot your password",
        sc: "send code",
        ForGetCodeERror: "correct code",
        errPass: "Incorrect email or password",
        code: "code",
        SendNow: "send now",
        FreeSendDesc: `You can send free messages to your friends and family`,
        SMSRemains: "Keeping messages",
        Profile: "Profile personly",
        update: "Update",
        fail: "Fail",
        success: "Success",
        ContectUs: "Connect with us",
        subject: "Subject",
        choose: "Choose",
        feedback: "Feedback",
        rab: "Report a problem",
        fq: "Specification request",
        message: "the message",
        SendDesc: `Send your text message to anyone around the world for free through our website
        International SMS service. Send free SMS messages instantly
        With incredibly fast SMS service. The world is better and
        The fastest online text messaging service!`,
        earnDesc:
            "Now you can earn more free messages. Share this link with your friends, earn messages, and they will also get a new message.",
        link: "Your link",
        DashBoard: "DashBoard",
        logout: "logout",
        home: "home",
        sendsms: "Send sms",
        freeSms: "Free sms",
        Products: "Products"
    }
};
